apprise_url: 'https://apprise.3os.re/notify'
urls:
  - tgram://5098160709:AAH1kFSKpcIkdnkoCvkwtvvJXiOjLjdu7dk/-761743928/
  # - discord://WebhookID/WebhookToken
  # - slack://TokenA/TokenB/TokenC
  # - twilio://ACCTSID:AUTH_TOKEN@FromPhone/ToPhone
  # - mailto://user:pass@mailserver:port?to=email@domain.com&from=email@domain.com
  # - msteams://Webhook_URL
  # - growl://password@hostname
  # - pover://user_key@/device/
  # - pbul://access_token/
  # - ifttt://webhook_id/webhook_event/
  # - join://api_key/
  # - prowl://apikey/
  # - json://hostname:port/
  # - kodi://user:pass@hostname:port/
  # - mmost://Webhook_URL/
  # - ryver://organization/workflow_bot_token/
  # - zulip://bot_email:bot_api_token@organization/
  # - rocketchat://user:password@hostname:port/channel/
  # - ncloud://user:password@hostname/
  # - gotify://hostname:port@App_Token
  # - faast://authorization_token/
  # - emby://user:password@hostname:port/
  # - plex://user:password@hostname:port/
  # - popcorn://user:password@hostname:port/
  # - xbmc://user:password@hostname:port/
  # - sns://access_key:secret_key@TopicArn/
  # - dingtalk://access_token/
  # - feishu://webhook/
